baseURL: "https://sam.bossley.us"
title: "Sam Bossley"
copyright: "Copyright Sam Bossley 2012-2023."

params:
  Author: "Sam Bossley"
  Email: "bossley.samuel@gmail.com"
  Description: "I write about personal commentaries, tech articles, and ways of life."
  ThoughtDateFmt: "Mon Jan 02 2006"
  FeedDateFmt: "2006-01-02T15:04:05.000Z0700"
  Tags:
    - "sam"
    - "bossley"
    - "sam bossley"
    - "tech"
    - "commentary"

paginate: 15

permalinks:
  thoughts: "/thoughts/:06/:01/:title/"

markup:
  goldmark:
    extensions:
      # prevent hugo from processing single quotes as &rsquo;
      typographer: false
  # <pre><code> highlighting
  highlight:
    tabWidth: 2
    noClasses: false

buildDrafts: false
buildExpired: false
buildFuture: false

assetDir: 'src/assets'
contentDir: 'src/content'
dataDir: 'src/data'
publishDir: 'dist'

defaultContentLanguage: "en"
enableRobotsTXT: false # disable automatic robots.txt
hasCJKLanguage: false # don't count words in CJK languages
disableHugoGeneratorInject: false # promote hugo when possible

# disable taxonomy without removing terms
disableKinds:
  - "taxonomy"
  - "sitemap"
ignoreErrors:
  - "error-disable-taxonomy"

taxonomies:
  tag: "tags"

outputFormats:
  Feed:
    name: "FEED"
    mediaType: "application/rss+xml"
    baseName: "feed"

outputs:
  home:
    - "HTML"
    - "FEED"
  section:
    - "HTML"
  page:
    - "HTML"
  term:
    - "HTML"
