#!/bin/sh
# vim:fdm=marker
# formats errors for most webservers

dir="$1"
errors="403 404"

for err in $errors; do
  root="${dir}/${err}"
  mv "${root}/index.html" "${root}.html"
  mv "${root}/index.gmi" "${root}.gmi"
  rm -r "${root}"
done
