#!/usr/bin/env sh
# convert entire project folders from html to gemini
# vim:fdm=marker

# geminject {{{

geminject() {
  local file="$1"
  local outFile="$2"
  local src="$3"

  data="$(cat "$src")"

  # remove front matter
  # (assumption: front matter exists)
  data="${data#*---}"
  matter="${data%%---*}"
  data="${data#*---}"

  title="${matter##*title:\ }"
  title="$(echo "$title" | head -n 1)"
  title="${title#\"}"
  title="${title%\"}"

  date="${matter##*date:\ }"
  date="$(echo "$date" | head -n 1)"

  header="# ${title}\n\n${date}\n"
  footer="=> / Copyright Sam Bossley $(date "+%Y")"

  echo "${header}${data}\n\n${footer}" > "$outFile"
}

# }}}

# geminizefile {{{

geminizefile() {
  local file="$1"
  local outFile="$2"
  local src="$3"

  case "$file" in
    *".html")
      outMod="${outFile%.*}.gmi"
      if [ -f "$src" ]; then
        geminject "$file" "$outMod" "$src"
        echo "injected '${file}' -> '${outMod}'"
      else
        node ./scripts/html2gmi.js "$file" "$outMod"
        echo "converted '${file}' -> '${outMod}'"
      fi
      ;;
    # passthrough for non-html files
    *) cp -v "$file" "$outFile" ;;
  esac
}

# }}}

# geminizedir {{{

geminizedir() {
  local dir="$1"
  local outDir="$2"
  local src="$3"

  mkdir -p "$outDir"

  for file in $(ls -a "$dir"); do
    path="${dir}/${file}"
    outPath="${outDir}/${file}"
    srcPath="${src}/${file}"

    if ! [ "$file" = "." ] && ! [ "$file" = ".." ]; then
      if [ -d "$path" ]; then
        geminizedir "$path" "$outPath" "$srcPath"
      else
        gmi="${srcPath%\/*}.gmi"
        geminizefile "$path" "$outPath" "$gmi"
      fi
    fi
  done
}

# }}}

# main {{{

src="$(pwd)"
dir="${src}/_site"
outDir="${src}/_site_gemini"

geminizedir "$dir" "$outDir" "$src"

echo "done"

# }}}
