#!/bin/sh
# vim:fdm=marker
# generates a separate gemini project directory from initial HTML output
# the goal is to remove static assets and reduce the overall size of the gemini project

STATIC_PATH="/static"

ignorePath="${1}${STATIC_PATH}"

# extract baseURL
baseURL="$(grep "baseURL" "config.yml")"
baseURL="https${baseURL##*https}"
baseURL="${baseURL%*"'"}"

mkdir -p "$2"

for file in $(find "$1" -type f -name *.gmi); do
  # ignore files from static/static dir
  if [ "${file#"${ignorePath}"}" != "$file" ]; then
    continue
  fi

  relFile="${file#"${1}"/}"
  relPath="${relFile%/*}"

  # path is different than file path
  # (aka if folders need to be created)
  if [ "$relPath" != "${relFile}" ]; then
    mkdir -p "${2}/${relFile%/*}"
  fi

  output="${2}/${relFile}"
  mv "$file" "$output"
  # replace rel urls with abs urls for static asset refs
  sed -i -e "s#^=> ${STATIC_PATH}#=> ${baseURL}${STATIC_PATH}#g" "$output"
done
